package com.servlet.bank;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class FixedDepositApplicationServlet
 */
@WebServlet("/fixeddepositapplicationpage")
public class FixedDepositApplicationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public FixedDepositApplicationServlet() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		PrintWriter pw = response.getWriter();
		pw.println("<head>"
				+ "    <meta charset='UTF-8'>"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
				+ "    <title>Fixed Deposit Application</title>"
				+ "    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
				+ "    <!-- Use absolute path or context-relative path for your servlet environment -->"
				+ "    <link rel='stylesheet' href='fixeddeposit.css'>"
				+ "</head>");
		pw.println("<body>"
				+ "    <div class='container'>"
				+ "        <header>"
				+ "            <h1><i class='fas fa-piggy-bank'></i> Fixed Deposit Application</h1>"
				+ "            <p>Secure your savings with our fixed deposit scheme. Enjoy guaranteed returns with attractive interest rates.</p>"
				+ "        </header>"
				+ "        "
				+ "        <div class='card-container'>"
				+ "            <div class='card form-card'>"
				+ "                <div class='card-header'>"
				+ "                    <h2><i class='fas fa-file-alt'></i> Deposit Information</h2>"
				+ "                </div>"
				+ "                "
				+ "                <form id='depositForm'>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='amount'><i class='fas fa-money-bill-wave info-icon'></i> Deposit Amount (₹)</label>"
				+ "                        <input type='number' id='amount' min='1000' max='10000000' value='50000' required>"
				+ "                        <div class='range-container'>"
				+ "                            <input type='range' id='amountRange' min='1000' max='1000000' value='50000' step='1000'>"
				+ "                            <span class='range-value'>₹50,000</span>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='tenure'><i class='fas fa-calendar-alt info-icon'></i> Tenure</label>"
				+ "                        <div class='range-container'>"
				+ "                            <input type='range' id='tenure' min='3' max='120' value='12' step='1'>"
				+ "                            <span class='range-value'>12 months</span>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='interestRate'><i class='fas fa-percentage info-icon'></i> Interest Rate (% per annum)</label>"
				+ "                        <div class='range-container'>"
				+ "                            <input type='range' id='interestRate' min='1' max='15' value='6.5' step='0.1'>"
				+ "                            <span class='range-value'>6.5%</span>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='interestPayout'><i class='fas fa-coins info-icon'></i> Interest Payout</label>"
				+ "                        <select id='interestPayout'>"
				+ "                            <option value='monthly'>Monthly</option>"
				+ "                            <option value='quarterly'>Quarterly</option>"
				+ "                            <option value='halfYearly'>Half-Yearly</option>"
				+ "                            <option value='annually'>Annually</option>"
				+ "                            <option value='maturity' selected>At Maturity</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='name'><i class='fas fa-user info-icon'></i> Full Name</label>"
				+ "                        <input type='text' id='name' placeholder='Enter your full name' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='email'><i class='fas fa-envelope info-icon'></i> Email Address</label>"
				+ "                        <input type='email' id='email' placeholder='Enter your email' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='phone'><i class='fas fa-phone info-icon'></i> Phone Number</label>"
				+ "                        <input type='tel' id='phone' placeholder='Enter your phone number' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <button type='submit' class='btn'><i class='fas fa-calculator'></i> Calculate & Apply for FD</button>"
				+ "                </form>"
				+ "            </div>"
				+ "            "
				+ "            <div class='card'>"
				+ "                <div class='card-header'>"
				+ "                    <h2><i class='fas fa-chart-line'></i> Maturity Details</h2>"
				+ "                </div>"
				+ "                "
				+ "                <div class='result-content'>"
				+ "                    <div class='result-item'>"
				+ "                        <span class='result-label'>Principal Amount:</span>"
				+ "                        <span class='result-value' id='principalValue'>₹50,000.00</span>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='result-item'>"
				+ "                        <span class='result-label'>Tenure:</span>"
				+ "                        <span class='result-value' id='tenureValue'>12 months</span>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='result-item'>"
				+ "                        <span class='result-label'>Interest Rate:</span>"
				+ "                        <span class='result-value' id='rateValue'>6.5% per annum</span>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='result-item'>"
				+ "                        <span class='result-label'>Interest Earned:</span>"
				+ "                        <span class='result-value' id='interestValue'>₹3,250.00</span>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='progress-container'>"
				+ "                        <div class='progress-bar' id='progressBar'></div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='maturity-value' id='maturityValue'>"
				+ "                        ₹53,250.00"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='interest-breakdown'>"
				+ "                        <h3>Interest Composition</h3>"
				+ "                        <div class='result-item'>"
				+ "                            <span class='result-label'>Principal:</span>"
				+ "                            <span class='result-value'>94%</span>"
				+ "                        </div>"
				+ "                        <div class='result-item'>"
				+ "                            <span class='result-label'>Interest:</span>"
				+ "                            <span class='result-value'>6%</span>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                </div>"
				+ "            </div>"
				+ "        </div>"
				+ "        "
				+ "        <div class='terms'>"
				+ "            <h2><i class='fas fa-info-circle'></i> Fixed Deposit Terms</h2>"
				+ "            <ul>"
				+ "                <li>Minimum deposit amount: <span class='highlight'>₹5,000</span></li>"
				+ "                <li>Minimum tenure: <span class='highlight'>3 months</span></li>"
				+ "                <li>Maximum tenure: <span class='highlight'>10 years</span></li>"
				+ "                <li>Premature withdrawal is allowed with a penalty of <span class='highlight'>1%</span> on the interest earned</li>"
				+ "                <li>Interest rates are subject to change as per RBI guidelines</li>"
				+ "                <li>TDS (Tax Deducted at Source) is applicable on interest earned as per current tax laws</li>"
				+ "                <li>Senior citizens are eligible for an additional <span class='highlight'>0.5%</span> interest</li>"
				+ "            </ul>"
				+ "        </div>"
				+ "    </div>"
				+ "    "
				+ "    <script>"
				+ "        document.addEventListener('DOMContentLoaded', function() {"
				+ "            // Get DOM elements"
				+ "            const amountInput = document.getElementById('amount');"
				+ "            const amountRange = document.getElementById('amountRange');"
				+ "            const amountValue = document.querySelector('.range-value:first-of-type');"
				+ "            "
				+ "            const tenureInput = document.getElementById('tenure');"
				+ "            const tenureValue = document.querySelector('.range-value:nth-of-type(2)');"
				+ "            "
				+ "            const interestInput = document.getElementById('interestRate');"
				+ "            const interestValue = document.querySelector('.range-value:last-of-type');"
				+ "            "
				+ "            const principalValue = document.getElementById('principalValue');"
				+ "            const tenureDisplay = document.getElementById('tenureValue');"
				+ "            const rateDisplay = document.getElementById('rateValue');"
				+ "            const interestDisplay = document.getElementById('interestValue');"
				+ "            const maturityDisplay = document.getElementById('maturityValue');"
				+ "            const progressBar = document.getElementById('progressBar');"
				+ "            "
				+ "            // Initialize values"
				+ "            updateAmountDisplay();"
				+ "            updateTenureDisplay();"
				+ "            updateInterestDisplay();"
				+ "            calculateFD();"
				+ "            "
				+ "            // Event listeners for range inputs"
				+ "            amountInput.addEventListener('input', function() {"
				+ "                amountRange.value = this.value;"
				+ "                updateAmountDisplay();"
				+ "                calculateFD();"
				+ "            });"
				+ "            "
				+ "            amountRange.addEventListener('input', function() {"
				+ "                amountInput.value = this.value;"
				+ "                updateAmountDisplay();"
				+ "                calculateFD();"
				+ "            });"
				+ "            "
				+ "            tenureInput.addEventListener('input', function() {"
				+ "                updateTenureDisplay();"
				+ "                calculateFD();"
				+ "            });"
				+ "            "
				+ "            interestInput.addEventListener('input', function() {"
				+ "                updateInterestDisplay();"
				+ "                calculateFD();"
				+ "            });"
				+ "            "
				+ "            // Form submission"
				+ "            document.getElementById('depositForm').addEventListener('submit', function(e) {"
				+ "                e.preventDefault();"
				+ "                alert('Fixed deposit application submitted successfully!\\nOur representative will contact you shortly.');"
				+ "                // In a real application, this would send the data to a server"
				+ "            });"
				+ "            "
				+ "            // Update functions"
				+ "            function updateAmountDisplay() {"
				+ "                const amount = parseInt(amountInput.value);"
				+ "                amountValue.textContent = '₹' + amount.toLocaleString('en-IN');"
				+ "                principalValue.textContent = '₹' + amount.toLocaleString('en-IN');"
				+ "            }"
				+ "            "
				+ "            function updateTenureDisplay() {"
				+ "                const months = parseInt(tenureInput.value);"
				+ "                tenureValue.textContent = months + ' months';"
				+ "                "
				+ "                if (months < 12) {"
				+ "                    tenureDisplay.textContent = months + ' months';"
				+ "                } else {"
				+ "                    const years = months / 12;"
				+ "                    tenureDisplay.textContent = years.toFixed(1) + ' years';"
				+ "                }"
				+ "            }"
				+ "            "
				+ "            function updateInterestDisplay() {"
				+ "                const rate = parseFloat(interestInput.value);"
				+ "                interestValue.textContent = rate.toFixed(1) + '%';"
				+ "                rateDisplay.textContent = rate.toFixed(1) + '% per annum';"
				+ "            }"
				+ "            "
				+ "            // Calculate FD maturity amount"
				+ "            function calculateFD() {"
				+ "                const principal = parseFloat(amountInput.value);"
				+ "                const months = parseInt(tenureInput.value);"
				+ "                const rate = parseFloat(interestInput.value) / 100;"
				+ "                const years = months / 12;"
				+ "                "
				+ "                // Simple interest calculation (for simplicity)"
				+ "                // In real applications, compound interest would be used based on payout frequency"
				+ "                const interest = principal * rate * years;"
				+ "                const maturity = principal + interest;"
				+ "                "
				+ "                // Update display"
				+ "                interestDisplay.textContent = '₹' + interest.toFixed(2);"
				+ "                maturityDisplay.textContent = '₹' + maturity.toLocaleString('en-IN', {minimumFractionDigits: 2, maximumFractionDigits: 2});"
				+ "                "
				+ "                // Update progress bar"
				+ "                const interestPercentage = (interest / maturity) * 100;"
				+ "                progressBar.style.width = interestPercentage + '%';"
				+ "            }"
				+ "        });"
				+ "    </script>"
				+ "</body>"
				+ "");
	}
	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
