package com.servlet.bank;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class HomeInsuranceApplicationServlet
 */
@WebServlet("/homeinsuranceapplicationpage")
public class HomeInsuranceApplicationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public HomeInsuranceApplicationServlet() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		
		PrintWriter pw = response.getWriter();
		response.setContentType("text/html");
	    long acno = (Long) request.getSession().getAttribute("accountno");
		request.getSession().setAttribute("typeofinsurance", "homeinsurance");
		pw.println("<head>"
				+ "    <meta charset='UTF-8'>"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
				+ "    <title>Home Insurance Application</title>"
				+ "    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
				+ "    <link rel='stylesheet' href='homeinsurancecss.css'>"
				+ "</head>");
		pw.println("<body>"
				+ "    <div class='container'>"
				+ "        <a href='insuranceapplicationshubpage' class='back-btn'><i class='fas fa-arrow-left'></i> Back to Insurance Hub</a>"
				+ "        <header>"
				+ "            <h1><i class='fas fa-home'></i> Home Insurance Application</h1>"
				+ "            <p>Protect your home and belongings against unforeseen events</p>"
				+ "        </header>"
				+ "        <form class='form-card' method='post' action='insuranceapplicationsubmissionpage'>"
				+ "            <div class='form-header'>"
				+ "                <h2><i class='fas fa-file-alt'></i> Application Form</h2>"
				+ "            </div>"
				+ "            <div class='form-container'>"
				+ "                <div class='form-section'>"
				+ "                    <h3><i class='fas fa-home'></i> Property Details</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='property-type'>Property Type</label>"
				+ "                        <select name='propertytype' required>"
				+ "                            <option value=''>Select</option>"
				+ "                            <option value='house'>Independent House</option>"
				+ "                            <option value='apartment'>Apartment</option>"
				+ "                            <option value='villa'>Villa</option>"
				+ "                            <option value='farmhouse'>Farmhouse</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-row'>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='built-year'>Year Built</label>"
				+ "                            <input type='number' name='builtyear' min='1950' max='2023' required>"
				+ "                        </div>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='area'>Built-up Area (sq. ft.)</label>"
				+ "                            <input type='number' name='area' required>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='property-address'>Property Address</label>"
				+ "                        <textarea name='propertyaddress' rows='3' required></textarea>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='property-value'>Current Market Value (₹)</label>"
				+ "                        <input type='number' name='propertyvalue' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='contents-value'>Contents Value (₹)</label>"
				+ "                        <input type='number' name='contentsvalue' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <h3><i class='fas fa-user'></i> Owner Information</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='home-owner'>Owner Name</label>"
				+ "                        <input type='text' name='homeowner' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-row'>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='home-phone'>Phone Number</label>"
				+ "                            <input type='tel' name='phone' required>"
				+ "                        </div>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='home-email'>Email Address</label>"
				+ "                            <input type='email' name='email' required>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                </div>"
				+ "                "
				+ "                <div class='form-section'>"
				+ "                    <h3><i class='fas fa-cogs'></i> Coverage Details</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='coverage-type-home'>Coverage Type</label>"
				+ "                        <select name='coveragetypehome' required>"
				+ "                            <option value=''>Select</option>"
				+ "                            <option value='structure'>Structure Only</option>"
				+ "                            <option value='contents'>Contents Only</option>"
				+ "                            <option value='both'>Structure + Contents</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='home-addons'>Additional Protections</label>"
				+ "                        <select nmae='homeaddons' multiple>"
				+ "                            <option value='earthquake'>Earthquake</option>"
				+ "                            <option value='flood'>Flood</option>"
				+ "                            <option value='burglary'>Burglary/Theft</option>"
				+ "                            <option value='liability'>Personal Liability</option>"
				+ "                            <option value='valuables'>Valuables Coverage</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='info-box'>"
				+ "                        <p><i class='fas fa-info-circle'></i> Premium based on property value, location, coverage type and add-ons selected.</p>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='premium-box'>"
				+ "                        <div class='premium-header'>"
				+ "                            <h3>Estimated Annual Premium</h3>"
				+ "                            <i class='fas fa-calculator'></i>"
				+ "                        </div>"
				+ "                        <div class='premium-value' ='home-premium'>₹ --</div>"
				+ "                        "
				+ "                        <div class='premium-details'>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Property Value</div>"
				+ "                                <div class='value' name='propertyvalue-display'>--</div>"
				+ "                            </div>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Contents Value</div>"
				+ "                                <div class='value' name='contentsvalue-display'>--</div>"
				+ "                            </div>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Add-ons</div>"
				+ "                                <div class='value' name='homeaddons-display'>0</div>"
				+ "                            </div>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <h3><i class='fas fa-shield-alt'></i> Security Features</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='security'>Security System</label>"
				+ "                        <select name='securitysystem' required>"
				+ "                            <option value='none'>None</option>"
				+ "                            <option value='basic'>Basic (Door Locks)</option>"
				+ "                            <option value='alarm'>Alarm System</option>"
				+ "                            <option value='monitored'>Monitored Security System</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='fire-ext'>Fire Extinguishers</label>"
				+ "                        <select name='fireextin' required>"
				+ "                            <option value='no'>No</option>"
				+ "                            <option value='yes'>Yes</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='policy-start-home'>Policy Start Date</label>"
				+ "                        <input type='date' name='policystart-home' required>"
				+ "                    </div>"
				+ "                </div>"
				+ "            </div>"
				+ "            <div class='terms'>"
				+ "                <h3><i class='fas fa-info-circle'></i> Terms & Conditions</h3>"
				+ "                <ul>"
				+ "                    <li>Policy is valid for <span class='highlight'>1 year</span> from the start date</li>"
				+ "                    <li>Claims must be reported within <span class='highlight'>7 days</span> of the incident</li>"
				+ "                    <li>Standard exclusions include war, nuclear risks, and wear & tear</li>"
				+ "                    <li>Underinsurance clause applies if property is insured for less than 80% of its value</li>"
				+ "                    <li>Policy renewal must be completed before expiration date</li>"
				+ "                </ul>"
				+ "            </div>"
				+ "            <div class='btn-container'>"
				+ "                <button class='btn' type='submit'><i class='fas fa-file-signature'></i> Submit Application</button>"
				+ "            </div>"
				+ "        </form>"
				+ "    </div>"
				+ "    <script>"
				+ "        document.addEventListener('DOMContentLoaded', function() {"
				+ "            // Home insurance premium calculation"
				+ "            document.getElementById('property-value').addEventListener('input', calculateHomePremium);"
				+ "            document.getElementById('contents-value').addEventListener('input', calculateHomePremium);"
				+ "            document.getElementById('coverage-type-home').addEventListener('change', calculateHomePremium);"
				+ "            document.getElementById('home-addons').addEventListener('change', calculateHomePremium);"
				+ "            "
				+ "            // Initial calculation"
				+ "            calculateHomePremium();"
				+ "        });"
				+ "        function calculateHomePremium() {"
				+ "            const propertyValue = parseInt(document.getElementById('property-value').value) || 0;"
				+ "            const contentsValue = parseInt(document.getElementById('contents-value').value) || 0;"
				+ "            const coverageType = document.getElementById('coverage-type-home').value;"
				+ "            const addons = document.getElementById('home-addons').selectedOptions.length;"
				+ "            "
				+ "            if ((!propertyValue && coverageType !== 'contents') || (!contentsValue && coverageType !== 'structure') || !coverageType) {"
				+ "                document.getElementById('home-premium').textContent = '₹ --';"
				+ "                return;"
				+ "            }"
				+ "            "
				+ "            // Base premium calculation (simplified)"
				+ "            let basePremium = 0;"
				+ "            "
				+ "            if (coverageType === 'both') {"
				+ "                basePremium = (propertyValue * 0.0015) + (contentsValue * 0.002);"
				+ "            } else if (coverageType === 'structure') {"
				+ "                basePremium = propertyValue * 0.0015;"
				+ "            } else {"
				+ "                basePremium = contentsValue * 0.002;"
				+ "            }"
				+ "            "
				+ "            // Addons cost"
				+ "            basePremium += addons * 800;"
				+ "            "
				+ "            // Display results"
				+ "            document.getElementById('home-premium').textContent = '₹' + Math.round(basePremium).toLocaleString('en-IN');"
				+ "            document.getElementById('property-value-display').textContent = '₹' + propertyValue.toLocaleString('en-IN');"
				+ "            document.getElementById('contents-value-display').textContent = '₹' + contentsValue.toLocaleString('en-IN');"
				+ "            document.getElementById('home-addons_count').textContent = addons;"
				+ "        }"
				+ "    </script>"
				+ "    <script src='homeinsurancecss.js'></script>"
				+ "</body>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}