package com.servlet.bank;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class LifeInsuranceApplicationServlet
 */
@WebServlet("/lifeinsuranceapplicationpage")
public class LifeInsuranceApplicationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public LifeInsuranceApplicationServlet() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		long acno = (Long) request.getSession().getAttribute("accountno");
		request.getSession().setAttribute("typeofinsurance", "lifeinsurance");
		
		PrintWriter pw = response.getWriter();
		pw.println("<head>"
				+ "    <meta charset='UTF-8'>"
				+ "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
				+ "    <title>Life Insurance Application</title>"
				+ "    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
				+ "    <link rel='stylesheet' href='lifeinsurancecss.css'>"
				+ "</head>");
		pw.println("<body>"
				+ "    <div class='container'>"
				+ "        <a href='insuranceapplicationshubpage' class='back-btn'><i class='fas fa-arrow-left'></i> Back to Insurance Hub</a>"
				+ "        <header>"
				+ "            <h1><i class='fas fa-heartbeat'></i> Life Insurance Application</h1>"
				+ "            <p>Secure your family's future with our comprehensive life insurance plans</p>"
				+ "        </header>"
				+ "        <form class='form-card' method='post' action='insuranceapplicationsubmissionpage'>"
				+ "            <div class='form-header'>"
				+ "                <h2><i class='fas fa-file-alt'></i> Application Form</h2>"
				+ "            </div>"
				+ "            <div class='form-container'>"
				+ "                <div class='form-section'>"
				+ "                    <h3><i class='fas fa-user'></i> Personal Information</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-fullname'>Full Name</label>"
				+ "                        <input type='text' name='fullname' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-row'>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='life-dob'>Date of Birth</label>"
				+ "                            <input type='date' name='dob' required>"
				+ "                        </div>"
				+ "                        <div class='form-group'>"
				+ "                            <label for='life-gender'>Gender</label>"
				+ "                            <select name='gender' required>"
				+ "                                <option value=''>Select</option>"
				+ "                                <option value='male'>Male</option>"
				+ "                                <option value='female'>Female</option>"
				+ "                                <option value='other'>Other</option>"
				+ "                            </select>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-occupation'>Occupation</label>"
				+ "                        <input type='text' name='occupation' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-income'>Annual Income (₹)</label>"
				+ "                        <input type='number' name='annualincome' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-address'>Address</label>"
				+ "                        <textarea name='address' rows='3' required></textarea>"
				+ "                    </div>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-income'>Phone No : </label>"
				+ "                        <input type='number' name='phone' required>"
				+ "                    </div>"				
				+ "                    "
				+ "                    <h3><i class='fas fa-file-medical'></i> Health Information</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-height'>Height (cm)</label>"
				+ "                        <input type='number' name='height' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-weight'>Weight (kg)</label>"
				+ "                        <input type='number' name='weight' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-smoker'>Are you a smoker?</label>"
				+ "                        <select name='smoker' required>"
				+ "                            <option value=''>Select</option>"
				+ "                            <option value='no'>No</option>"
				+ "                            <option value='yes'>Yes</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                </div>"
				+ "                "
				+ "                <div class='form-section'>"
				+ "                    <h3><i class='fas fa-cogs'></i> Policy Details</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-coverage'>Coverage Amount (₹)</label>"
				+ "                        <select name='totalcoverage' required>"
				+ "                            <option value=''>Select Coverage</option>"
				+ "                            <option value='500000'>₹5,00,000</option>"
				+ "                            <option value='1000000'>₹10,00,000</option>"
				+ "                            <option value='2000000'>₹20,00,000</option>"
				+ "                            <option value='5000000'>₹50,00,000</option>"
				+ "                            <option value='10000000'>₹1,00,00,000</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-term'>Policy Term (Years)</label>"
				+ "                        <select name='policyterm' required>"
				+ "                            <option value=''>Select Term</option>"
				+ "                            <option value='10'>10 Years</option>"
				+ "                            <option value='15'>15 Years</option>"
				+ "                            <option value='20'>20 Years</option>"
				+ "                            <option value='25'>25 Years</option>"
				+ "                            <option value='30'>30 Years</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-type'>Policy Type</label>"
				+ "                        <select name='policytype' required>"
				+ "                            <option value=''>Select Type</option>"
				+ "                            <option value='term'>Term Life Insurance</option>"
				+ "                            <option value='whole'>Whole Life Insurance</option>"
				+ "                            <option value='endowment'>Endowment Plan</option>"
				+ "                            <option value='ulip'>ULIP (Unit Linked Insurance Plan)</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='info-box'>"
				+ "                        <p><i class='fas fa-info-circle'></i> Premium will be calculated based on your age, coverage amount, policy term, and health factors.</p>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='premium-box'>"
				+ "                        <div class='premium-header'>"
				+ "                            <h3>Estimated Premium</h3>"
				+ "                            <i class='fas fa-calculator'></i>"
				+ "                        </div>"
				+ "                        <div class='premium-value' name='premium'>₹ --</div>"
				+ "                        "
				+ "                        <div class='premium-details'>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Coverage</div>"
				+ "                                <div class='value' name='coverage-display'>--</div>"
				+ "                            </div>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Term</div>"
				+ "                                <div class='value' name='policyterm-display'>--</div>"
				+ "                            </div>"
				+ "                            <div class='premium-detail'>"
				+ "                                <div class='label'>Type</div>"
				+ "                                <div class='value' name='policytype-display'>--</div>"
				+ "                            </div>"
				+ "                        </div>"
				+ "                    </div>"
				+ "                    "
				+ "                    <h3><i class='fas fa-users'></i> Beneficiary Information</h3>"
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-beneficiary'>Beneficiary Name</label>"
				+ "                        <input type='text' name='beneficiaryname' required>"
				+ "                    </div>"
				+ "                    "
				+ "                    <div class='form-group'>"
				+ "                        <label for='life-relation'>Relationship</label>"
				+ "                        <select name='relationwithbeneficiary' required>"
				+ "                            <option value=''>Select</option>"
				+ "                            <option value='spouse'>Spouse</option>"
				+ "                            <option value='child'>Child</option>"
				+ "                            <option value='parent'>Parent</option>"
				+ "                            <option value='sibling'>Sibling</option>"
				+ "                            <option value='other'>Other</option>"
				+ "                        </select>"
				+ "                    </div>"
				+ "                </div>"
				+ "            </div>"
				+ "            <div class='terms'>"
				+ "                <h3><i class='fas fa-info-circle'></i> Terms & Conditions</h3>"
				+ "                <ul>"
				+ "                    <li>Minimum entry age: <span class='highlight'>18 years</span>, Maximum entry age: <span class='highlight'>65 years</span></li>"
				+ "                    <li>Policy becomes effective after <span class='highlight'>30 days</span> from the date of issuance</li>"
				+ "                    <li>Suicide clause: Policy will not pay for suicide within <span class='highlight'>1 year</span> of policy start</li>"
				+ "                    <li>Medical examination may be required for coverage above ₹25,00,000</li>"
				+ "                    <li>Premium payments must be made annually by the due date</li>"
				+ "                </ul>"
				+ "            </div>"
				+ "            <div class='btn-container'>"
				+ "                <button class='btn' type='submit'><i class='fas fa-file-signature'></i> Submit Application</button>"
				+ "            </div>"
				+ "        </form>"
				+ "    </div>"
				+ "    <script>"
				+ "        document.addEventListener('DOMContentLoaded', function() {"
				+ "            // Life insurance premium calculation"
				+ "            document.getElementsByName('life-coverage')[0].addEventListener('change', calculateLifePremium);"
				+ "            document.getElementsByName('life-term')[0].addEventListener('change', calculateLifePremium);"
				+ "            document.getElementsByName('life-type')[0].addEventListener('change', calculateLifePremium);"
				+ "            document.getElementsByName('life-dob')[0].addEventListener('change', calculateLifePremium);"
				+ "            "
				+ "            // Initial calculation"
				+ "            calculateLifePremium();"
				+ "        });"
				+ "        function calculateLifePremium() {"
				+ "            const coverage = parseInt(document.getElementsByName('life-coverage')[0].value) || 0;"
				+ "            const term = parseInt(document.getElementsByName('life-term')[0].value) || 0;"
				+ "            const type = document.getElementsByName('life-type')[0].value;"
				+ "            const dob = document.getElementsByName('life-dob')[0].value;"
				+ "            "
				+ "            if (!coverage || !term || !type || !dob) {"
				+ "                document.getElementById('life-premium').textContent = '₹ --';"
				+ "                return;"
				+ "            }"
				+ "            "
				+ "            // Calculate age"
				+ "            const birthDate = new Date(dob);"
				+ "            const today = new Date();"
				+ "            let age = today.getFullYear() - birthDate.getFullYear();"
				+ "            const monthDiff = today.getMonth() - birthDate.getMonth();"
				+ "            if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {"
				+ "                age--;"
				+ "            }"
				+ "            "
				+ "            // Base premium calculation (simplified)"
				+ "            let basePremium = coverage / (term * 100);"
				+ "            "
				+ "            // Adjust for age"
				+ "            if (age < 25) basePremium *= 1.1;"
				+ "            else if (age < 40) basePremium *= 1.2;"
				+ "            else if (age < 55) basePremium *= 1.5;"
				+ "            else basePremium *= 2.0;"
				+ "            "
				+ "            // Adjust for policy type"
				+ "            if (type === 'whole') basePremium *= 1.8;"
				+ "            else if (type === 'endowment') basePremium *= 1.5;"
				+ "            else if (type === 'ulip') basePremium *= 1.3;"
				+ "            "
				+ "            // Display results"
				+ "            document.getElementById('life-premium').textContent = '₹' + Math.round(basePremium).toLocaleString('en-IN');"
				+ "            document.getElementById('life-coverage-display').textContent = '₹' + coverage.toLocaleString('en-IN');"
				+ "            document.getElementById('life-term-display').textContent = term + ' Years';"
				+ "            document.getElementById('life-type-display').textContent = document.querySelector('[name=life-type] option:checked').text;"
				+ "        }"
				+ "    </script>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}