package com.servlet.bank;

import java.io.IOException;
import java.io.PrintWriter;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class VehicleInsuranceApplicationServlet
 */
@WebServlet("/vehicleinsuranceapplicationpage")
public class VehicleInsuranceApplicationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public VehicleInsuranceApplicationServlet() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	    PrintWriter pw = response.getWriter();
	    response.setContentType("text/html");
	    long acno = (Long) request.getSession().getAttribute("accountno");
		request.getSession().setAttribute("typeofinsurance", "vehicleinsurance");
	    // Change all form elements from id="..." to name="..." and update JS accordingly
	    pw.println("<head>"
	    		+ "    <meta charset='UTF-8'>"
	    		+ "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
	    		+ "    <title>Vehicle Insurance Application</title>"
	    		+ "    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
	    		+ "    <link rel='stylesheet' href='vehicleinsurancecss.css'>"
	    		+ "</head>");
	    pw.println("<body>"
	    		+ "    <div class='container'>"
	    		+ "        <a href='insuranceapplicationshubpage' class='back-btn'><i class='fas fa-arrow-left'></i> Back to Insurance Hub</a>"
	    		+ "        <header>"
	    		+ "            <h1><i class='fas fa-car'></i> Vehicle Insurance Application</h1>"
	    		+ "            <p>Comprehensive coverage for your car, bike, or commercial vehicle</p>"
	    		+ "        </header>"
	    		+ "        <form class='form-card' method='post' action='insuranceapplicationsubmissionpage'>"
	    		+ "            <div class='form-header'>"
	    		+ "                <h2><i class='fas fa-file-alt'></i> Application Form</h2>"
	    		+ "            </div>"
	    		+ "            <div class='form-container'>"
	    		+ "                <div class='form-section'>"
	    		+ "                    <h3><i class='fas fa-car'></i> Vehicle Details</h3>"
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='vehicletype'>Vehicle Type</label>"
	    		+ "                        <select name='vehicletype' required>"
	    		+ "                            <option value=''>Select</option>"
	    		+ "                            <option value='car'>Car</option>"
	    		+ "                            <option value='bike'>Motorcycle</option>"
	    		+ "                            <option value='scooter'>Scooter</option>"
	    		+ "                            <option value='commercial'>Commercial Vehicle</option>"
	    		+ "                        </select>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-row'>"
	    		+ "                        <div class='form-group'>"
	    		+ "                            <label for='vehiclemake'>Make</label>"
	    		+ "                            <input type='text' name='vehiclemake' required>"
	    		+ "                        </div>"
	    		+ "                        <div class='form-group'>"
	    		+ "                            <label for='vehiclemodel'>Model</label>"
	    		+ "                            <input type='text' name='vehiclemodel' required>"
	    		+ "                        </div>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-row'>"
	    		+ "                        <div class='form-group'>"
	    		+ "                            <label for='vehicleyear'>Manufacturing Year</label>"
	    		+ "                            <input type='number' name='manufacturingyear' min='1990' max='2023' required>"
	    		+ "                        </div>"
	    		+ "                        <div class='form-group'>"
	    		+ "                            <label for='vehiclereg'>Registration Number</label>"
	    		+ "                            <input type='text' name='vehicleregnumber' required>"
	    		+ "                        </div>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='vehiclevalue'>Current Market Value (₹)</label>"
	    		+ "                        <input type='number' name='currentmarketvalue' required>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <h3><i class='fas fa-user'></i> Owner Information</h3>"
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='vehicleowner'>Owner Name</label>"
	    		+ "                        <input type='text' name='vehicleownername' required>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='vehiclelicense'>Driving License Number</label>"
	    		+ "                        <input type='text' name='drivinglicense' required>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='vehicleaddress'>Address</label>"
	    		+ "                        <textarea name='vehicleaddress' rows='3' required></textarea>"
	    		+ "                    </div>"
	    		+ "                </div>"
	    		+ "                "
	    		+ "                <div class='form-section'>"
	    		+ "                    <h3><i class='fas fa-cogs'></i> Coverage Details</h3>"
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='coveragetype'>Coverage Type</label>"
	    		+ "                        <select name='coveragetype' required>"
	    		+ "                            <option value=''>Select</option>"
	    		+ "                            <option value='comprehensive'>Comprehensive</option>"
	    		+ "                            <option value='thirdparty'>Third-Party Liability</option>"
	    		+ "                            <option value='owndamage'>Own Damage</option>"
	    		+ "                        </select>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='policyaddons'>Add-on Covers</label>"
	    		+ "                        <select name='policyaddons' multiple>"
	    		+ "                            <option value='zerodep'>Zero Depreciation</option>"
	    		+ "                            <option value='engine'>Engine Protection</option>"
	    		+ "                            <option value='ncb'>No Claim Bonus Protection</option>"
	    		+ "                            <option value='roadside'>Roadside Assistance</option>"
	    		+ "                            <option value='medical'>Medical Expenses</option>"
	    		+ "                        </select>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='info-box'>"
	    		+ "                        <p><i class='fas fa-info-circle'></i> Premium calculation based on vehicle type, age, value and coverage selected.</p>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='premium-box'>"
	    		+ "                        <div class='premium-header'>"
	    		+ "                            <h3>Estimated Premium</h3>"
	    		+ "                            <i class='fas fa-calculator'></i>"
	    		+ "                        </div>"
	    		+ "                        <div class='premium-value' name='vehiclepremium'>₹ --</div>"
	    		+ "                        "
	    		+ "                        <div class='premium-details'>"
	    		+ "                            <div class='premium-detail'>"
	    		+ "                                <div class='label'>Vehicle Value</div>"
	    		+ "                                <div class='value' name='vehiclevalue-display'>--</div>"
	    		+ "                            </div>"
	    		+ "                            <div class='premium-detail'>"
	    		+ "                                <div class='label'>Coverage</div>"
	    		+ "                                <div class='value' name='coveragetype-display'>--</div>"
	    		+ "                            </div>"
	    		+ "                            <div class='premium-detail'>"
	    		+ "                                <div class='label'>Add-ons</div>"
	    		+ "                                <div class='value' name='addons'>0</div>"
	    		+ "                            </div>"
	    		+ "                        </div>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <h3><i class='fas fa-history'></i> Claim History</h3>"
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='prevclaims'>Previous Claims (Last 3 Years)</label>"
	    		+ "                        <select name='prevclaims' required>"
	    		+ "                            <option value='0'>0</option>"
	    		+ "                            <option value='1'>1</option>"
	    		+ "                            <option value='2'>2</option>"
	    		+ "                            <option value='3'>3 or more</option>"
	    		+ "                        </select>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='ncb'>No Claim Bonus (NCB)</label>"
	    		+ "                        <select name='ncbonusclaims' required>"
	    		+ "                            <option value='0'>0% (New Policy)</option>"
	    		+ "                            <option value='20'>20% (1 claim-free year)</option>"
	    		+ "                            <option value='25'>25% (2 claim-free years)</option>"
	    		+ "                            <option value='35'>35% (3 claim-free years)</option>"
	    		+ "                            <option value='45'>45% (4 claim-free years)</option>"
	    		+ "                            <option value='50'>50% (5+ claim-free years)</option>"
	    		+ "                        </select>"
	    		+ "                    </div>"
	    		+ "                    "
	    		+ "                    <div class='form-group'>"
	    		+ "                        <label for='policystart'>Policy Start Date</label>"
	    		+ "                        <input type='date' name='policystart' required>"
	    		+ "                    </div>"
	    		+ "                </div>"
	    		+ "            </div>"
	    		+ "            <div class='terms'>"
	    		+ "                <h3><i class='fas fa-info-circle'></i> Terms & Conditions</h3>"
	    		+ "                <ul>"
	    		+ "                    <li>Policy is valid for <span class='highlight'>1 year</span> from the start date</li>"
	    		+ "                    <li>Claims must be reported within <span class='highlight'>48 hours</span> of the incident</li>"
	    		+ "                    <li>Depreciation applies to rubber, plastic, and fiber parts</li>"
	    		+ "                    <li>Third-party liability coverage is as per Motor Vehicles Act</li>"
	    		+ "                    <li>Own damage claims are subject to deductible/excess amount</li>"
	    		+ "                </ul>"
	    		+ "            </div>"
	    		+ "            <div class='btn-container'>"
	    		+ "                <button class='btn' type='submit'><i class='fas fa-file-signature'></i> Submit Application</button>"
	    		+ "            </div>"
	    		+ "        </form>"
	    		+ "    </div>"
	    		+ "    <script>"
	    		+ "        document.addEventListener('DOMContentLoaded', function() {"
	    		+ "            // Vehicle insurance premium calculation"
	    		+ "            document.getElementsByName('vehicletype')[0].addEventListener('change', calculateVehiclePremium);"
	    		+ "            document.getElementsByName('vehiclevalue')[0].addEventListener('input', calculateVehiclePremium);"
	    		+ "            document.getElementsByName('coveragetype')[0].addEventListener('change', calculateVehiclePremium);"
	    		+ "            document.getElementsByName('policyaddons')[0].addEventListener('change', calculateVehiclePremium);"
	    		+ "            document.getElementsByName('prevclaims')[0].addEventListener('change', calculateVehiclePremium);"
	    		+ "            document.getElementsByName('ncb')[0].addEventListener('change', calculateVehiclePremium);"
	    		+ "            "
	    		+ "            // Initial calculation"
	    		+ "            calculateVehiclePremium();"
	    		+ "        });"
	    		+ "        function calculateVehiclePremium() {"
	    		+ "            const vehicleValue = parseInt(document.getElementsByName('vehiclevalue')[0].value) || 0;"
	    		+ "            const coverageType = document.getElementsByName('coveragetype')[0].value;"
	    		+ "            const addons = document.getElementsByName('policyaddons')[0].selectedOptions.length;"
	    		+ "            const prevClaims = parseInt(document.getElementsByName('prevclaims')[0].value) || 0;"
	    		+ "            const ncb = parseInt(document.getElementsByName('ncb')[0].value) || 0;"
	    		+ "            "
	    		+ "            if (!vehicleValue || !coverageType) {"
	    		+ "                document.getElementById('vehicle-premium').textContent = '₹ --';"
	    		+ "                return;"
	    		+ "            }"
	    		+ "            "
	    		+ "            // Base premium calculation (simplified)"
	    		+ "            let basePremium = 0;"
	    		+ "            "
	    		+ "            if (coverageType === 'comprehensive') {"
	    		+ "                basePremium = vehicleValue * 0.035;"
	    		+ "            } else if (coverageType === 'thirdparty') {"
	    		+ "                basePremium = vehicleValue * 0.01;"
	    		+ "            } else {"
	    		+ "                basePremium = vehicleValue * 0.025;"
	    		+ "            }"
	    		+ "            "
	    		+ "            // Addons cost"
	    		+ "            basePremium += addons * 1200;"
	    		+ "            "
	    		+ "            // Previous claims adjustment"
	    		+ "            basePremium *= (1 + (prevClaims * 0.15));"
	    		+ "            "
	    		+ "            // NCB discount"
	    		+ "            basePremium *= (1 - (ncb / 100));"
	    		+ "            "
	    		+ "            // Display results"
	    		+ "            document.getElementById('vehicle-premium').textContent = '₹' + Math.round(basePremium).toLocaleString('en-IN');"
	    		+ "            document.getElementById('vehicle-value-display').textContent = '₹' + vehicleValue.toLocaleString('en-IN');"
	    		+ "            document.getElementById('coveragetype-display').textContent = document.querySelector('[name=coveragetype] option:checked').text;"
	    		+ "            document.getElementById('addonscount').textContent = addons;"
	    		+ "        }"
	    		+ "    </script>"
	    		+ "</body>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}